# inventory/staging/hosts.yml
---
all:
  children:
    proxmox_cluster:
      hosts:
        pve-staging:
          ansible_host: 192.168.2.101
          ansible_user: root
          node_type: standalone
          cluster_role: single
          
    docker_hosts:
      hosts:
        docker-staging:
          ansible_host: 192.168.2.201
          ansible_user: ubuntu
          vm_id: 100
          target_node: pve-staging
          proxmox_host: pve-staging
  
  vars:
    ansible_python_interpreter: /usr/bin/python3
    domain: staging.multiskilled.ai
    environment: staging