---
# Example Ansible role structure for Traefik
# Path: ansible/roles/traefik/tasks/main.yml

- name: Create directories for Traefik
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ traefik_config_dir }}"
    - "{{ traefik_config_dir }}/conf.d"
    - "{{ traefik_config_dir }}/dynamic"
    - "{{ traefik_certs_dir }}"
    - "{{ traefik_logs_dir }}"

- name: Create Traefik network
  docker_network:
    name: "{{ traefik_network }}"
    driver: bridge
  when: traefik_create_network | bool

- name: Create Docker Compose file for Traefik
  template:
    src: docker-compose.yml.j2
    dest: "{{ traefik_config_dir }}/docker-compose.yml"
    mode: '0644'
  notify: Restart Traefik

- name: Create Traefik static configuration
  template:
    src: traefik.yml.j2
    dest: "{{ traefik_config_dir }}/traefik.yml"
    mode: '0644'
  notify: Restart Traefik

- name: Create Traefik dynamic configuration
  template:
    src: "{{ item.src }}"
    dest: "{{ traefik_config_dir }}/{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: "middlewares.yml.j2", dest: "dynamic/middlewares.yml" }
    - { src: "tls.yml.j2", dest: "dynamic/tls.yml" }
  notify: Restart Traefik

- name: Deploy Traefik
  community.docker.docker_compose:
    project_src: "{{ traefik_config_dir }}"
    state: present
  register: traefik_deploy_result

- name: Ensure Traefik is running
  community.docker.docker_compose:
    project_src: "{{ traefik_config_dir }}"
    services: traefik
    state: present
  when: not traefik_deploy_result.changed


