# danny
---
- name: Discover Network Configuration
  hosts: all
  gather_facts: true
  tasks:

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv
        - git
        - ansible

    - name: Create a virtual environment
      command: python3 -m venv /opt/myenv

    - name: Install required Python packages
      pip:
        requirements: /opt/myenv/requirements.txt
        virtualenv: /opt/myenv

    - name: Start the application
      command: /opt/myenv/bin/python /path/to/your/app.py2
