# ansible/playbooks/netbox-import.yml
---
- name: Import existing infrastructure into Netbox
  hosts: localhost
  connection: local
  vars:
    netbox_url: "https://{{ hostvars[groups['netbox_hosts'][0]]['ansible_host'] }}"
    netbox_token: "{{ vault_netbox_token }}"
  tasks:
    - name: Import devices from inventory
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item }}"
          device_type: "{{ hostvars[item].device_type | default('server') }}"
          device_role: "{{ hostvars[item].device_role | default('server') }}"
          site: "{{ hostvars[item].site | default('main') }}"
          status: active
      loop: "{{ groups['all'] }}"
      when: "'netbox_hosts' not in group_names"