# ansible/playbooks/network-discovery.yml
---
- name: Discover Network Configuration
  hosts: all
  gather_facts: true
  tasks:
    - name: Gather network interface information
      ansible.builtin.setup:
        gather_subset:
          - network
      register: network_facts2

    - name: Save network configuration
      copy:
        content: "{{ network_facts2 | to_nice_yaml }}"
        dest: "{{ playbook_dir }}/inventory/current-state/{{ inventory_hostname }}-network.yml"
        mode: '0644'
