# ansible/playbooks/network-discovery.yml
---
- name: Discover Network Configuration
  hosts: production
  gather_facts: true
  tasks:
    - name: Gather network interface information
      ansible.builtin.setup:
        gather_subset:
          - network
      register: network_facts
    
    - name: Save network configuration
      local_action:
        module: copy
        content: "{{ network_facts | to_nice_yaml }}"
        dest: "{{ playbook_dir }}/inventory/{{ inventory_hostname }}-network.yml"
        mode: '0644'
        