# ansible/playbooks/security-hardening.yml
---
- name: Security Hardening for Proxmox
  hosts: proxmox_hosts
  become: true
  gather_facts: true
  
  tasks:
    - name: Configure SSH daemon
      template:
        src: templates/sshd_config.j2
        dest: /etc/ssh/sshd_config
        mode: '0600'
        validate: '/usr/sbin/sshd -t -f %s'
      notify: Restart SSH
      
    - name: Configure server-wide security limits
      template:
        src: templates/limits.conf.j2
        dest: /etc/security/limits.conf
        mode: '0644'
        
    - name: Configure sysctl parameters for security
      template:
        src: templates/sysctl-security.conf.j2
        dest: /etc/sysctl.d/99-security.conf
        mode: '0644'
      notify: Apply sysctl
      
    - name: Enable automatic security updates
      apt:
        name: unattended-upgrades
        state: present
        
    - name: Configure automatic security updates
      template:
        src: templates/50unattended-upgrades.j2
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        mode: '0644'
        
    - name: Configure Proxmox web UI security
      lineinfile:
        path: /etc/default/pveproxy
        regexp: '^ALLOW_FROM='
        line: 'ALLOW_FROM={{ proxmox_allowed_networks | join(",") }}'
        create: yes
      when: proxmox_allowed_networks is defined
      notify: Restart PVE Proxy
      
  handlers:
    - name: Restart SSH
      service:
        name: sshd
        state: restarted
        
    - name: Apply sysctl
      command: sysctl -p /etc/sysctl.d/99-security.conf
      
    - name: Restart PVE Proxy
      service:
        name: pveproxy
        state: restarted