# ansible/inventory/production/hosts.yml
---
all:
  children:
    proxmox_hosts:
      hosts:
        pve:
          ansible_host: 192.168.0.200  # Replace with your T440 IP
          ansible_user: root
          node_type: single
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'