# ansible/inventory/production/hosts.yml

all:
  children:
    proxmox_hosts:
      hosts:
        pve1:
          ansible_host: 192.168.0.200  # Replace with your T440 IP
          ansible_user: root
          ansible_ssh_pass: 'we are winners'
          node_type: single
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        domain: multiskilled.ai
        environment: production