# inventory/production/hosts.yml
---
all:
  children:
    proxmox_cluster:
      children:
        proxmox_existing:
          hosts:
            pve1:
              ansible_host: 192.168.1.101
              ansible_user: root
              node_type: existing
              cluster_role: master
        proxmox_new:
          hosts:
            pve2:
              ansible_host: 192.168.1.102
              ansible_user: root
              node_type: new
              cluster_role: node
              hostname: pve2
      vars:
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        cluster_name: ai-cluster
        cluster_network: 10.10.10.0/24
        
    docker_hosts:
      hosts:
        docker1:
          ansible_host: 192.168.1.201
          ansible_user: ubuntu
          vm_id: 100
          target_node: pve1
          proxmox_host: pve1
        docker2:
          ansible_host: 192.168.1.202
          ansible_user: ubuntu
          vm_id: 101
          target_node: pve2
          proxmox_host: pve2
          
    monitoring_hosts:
      hosts:
        monitor1:
          ansible_host: 192.168.1.210
          ansible_user: ubuntu
          vm_id: 110
          target_node: pve1
          proxmox_host: pve1

    vault_hosts:
      hosts:
        vault1:
          ansible_host: 192.168.1.220
          ansible_user: ubuntu
          vm_id: 120
          target_node: pve2
          proxmox_host: pve2
          
    netbox_hosts:
      hosts:
        netbox1:
          ansible_host: 192.168.1.230
          ansible_user: ubuntu
          vm_id: 130
          target_node: pve2
          proxmox_host: pve2

  vars:
    ansible_python_interpreter: /usr/bin/python3
    domain: multiskilled.ai
    timezone: UTC
    dns_servers:
      - 1.1.1.1
      - 8.8.8.8

